name: 检查habitica状态，及时购买HP补充剂同时金额不超过1千
on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* * * * *'
jobs:
  guard-the-habitica-hero:
    runs-on: ubuntu-latest
    steps:
      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 27.2
      - name: Check out emacs-habitica
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          repository: lujun9972/emacs-habitica
          path: emacs-habitica
      - name: Check out guard
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: Guard
      - name: guard-the-habitica-hero
        run: ./Guard/habiticaGuard.el
        env:
          HABITICA_TOKEN: ${{ secrets.HABITICA_TOKEN }}
          HABITICA_UUID: ${{ secrets.HABITICA_UUID }}
          HABITICA_ALLOCATE_STAT: ${{ secrets.HABITICA_ALLOCATE_STAT }}
          HABITICA_KEEP_GOLD: ${{ secrets.HABITICA_KEEP_GOLD }}
          HABITICA_DAILY_SKILLS: ${{ secrets.HABITICA_DAILY_SKILLS }}
